_wandb:
    value:
        cli_version: 0.25.0
        e:
            x3z3kjrrnu01sci43163ib9xy9p1yv09:
                args:
                    - -d
                    - mnist
                    - -e
                    - "10"
                    - -b
                    - "64"
                    - -o
                    - momentum
                    - -lr
                    - "0.01"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - -a
                    - relu
                    - -wi
                    - xavier
                    - -l
                    - cross_entropy
                    - --run_name
                    - loss-crossentropy
                codePath: src/train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "52525297664"
                        used: "21564325888"
                email: da25m028@smail.iitm.ac.in
                executable: /home/harendra/Desktop/DL assignment 1/da6401_assignment_1/venv/bin/python
                git:
                    commit: c59c9e42634fabb60a51a4edb443fb44d233782f
                    remote: https://github.com/Singara-Harendra/DA6401-Assignment-1
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-62da593c-d767-9c08-740b-24f5035554e2
                host: harendra-Aspire-A715-51G
                memory:
                    total: "8014782464"
                os: Linux-6.8.0-101-generic-x86_64-with-glibc2.35
                program: /home/harendra/Desktop/DL assignment 1/da6401_assignment_1/src/train.py
                python: CPython 3.10.12
                root: /home/harendra/Desktop/DL assignment 1/da6401_assignment_1/src
                startedAt: "2026-03-06T13:59:11.166197Z"
                writerId: x3z3kjrrnu01sci43163ib9xy9p1yv09
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value:
        - 128
learning_rate:
    value: 0.01
loss:
    value: cross_entropy
model_save_path:
    value: best_model.npy
no_wandb:
    value: false
num_layers:
    value: 3
optimizer:
    value: momentum
run_name:
    value: loss-crossentropy
wandb_entity:
    value: null
wandb_project:
    value: da6401-mlp
weight_decay:
    value: 0
weight_init:
    value: xavier
